/**
 * Condition and action (ACE) validation against the definitions Construct
 * itself ships. The catalogue in ace-catalog-data.ts is generated by
 * scripts/build-ace-catalog.mjs from the editor's own files for one release.
 *
 * Built-in plugins and behaviors are checked against the catalogue, and a
 * third-party addon against its own definitions once they are loaded
 * (addon-definitions.ts). An ACE of an addon with no definitions loaded, or
 * of an object this project does not declare, is skipped rather than
 * reported, because nothing can know it; validate_project names such addons.
 */

import type { Construct3ProjectReader } from './project-reader.js';
import { ACE_CATALOG } from './ace-catalog-data.js';
import { addonDefinition } from './addon-definitions.js';

export interface AceParam {
  id: string;
  type: string;
  /** The choices of a combo parameter, as the event stores them. */
  items?: string[];
}

/** An expression as an expression string names it: its name, parameter types, and whether more arguments may follow. */
export interface ExpressionDef {
  name: string;
  params: string[];
  variadic?: boolean;
  returns?: string;
}

export interface AceSet {
  conditions: Record<string, AceParam[]>;
  actions: Record<string, AceParam[]>;
  /** Expressions by ID; the `name` is the form written in expression strings. */
  expressions: Record<string, ExpressionDef>;
}

export interface AceCatalog {
  /** The Construct release the catalogue was built from, e.g. r495-2. */
  release: string;
  /** Built-in plugins by plugin ID; "system" holds the System object's ACEs. */
  plugins: Record<string, AceSet>;
  /** Built-in behaviors by behavior ID. */
  behaviors: Record<string, AceSet>;
  /** ACEs the editor adds to plugins by capability (instance variables, position, hierarchy, ...). */
  common: AceSet;
}

export type AceKind = 'conditions' | 'actions';

export type AceProblemCode = 'unknown-ace' | 'unknown-parameter' | 'missing-parameter' | 'invalid-choice';

export interface AceProblem {
  code: AceProblemCode;
  message: string;
}

/** The release name as Construct shows it: r495-2 becomes r495.2. */
export const ACE_CATALOG_RELEASE = ACE_CATALOG.release.replace('-', '.');

/** Where an ACE is defined: a plugin (the System object is plugin "system") or a behavior. */
export type AceOwner = { kind: 'plugin'; id: string } | { kind: 'behavior'; id: string };

/** True when the built-in catalogue defines this plugin or behavior. */
export function isBuiltInAddon(kind: 'plugin' | 'behavior', id: string, catalog: AceCatalog = ACE_CATALOG): boolean {
  return kind === 'plugin' ? id in catalog.plugins : id in catalog.behaviors;
}

/** True when the ACEs of this owner can be checked: built in, or loaded from the addon's own definitions. */
export function hasAceDefinitions(owner: AceOwner, catalog: AceCatalog = ACE_CATALOG): boolean {
  return isBuiltInAddon(owner.kind, owner.id, catalog) || addonDefinition(owner.kind, owner.id) !== undefined;
}

/**
 * The definition of one ACE, or undefined when the owner is known and has no
 * such ACE, or null when the owner is neither in the catalogue nor among the
 * loaded third-party definitions.
 */
function lookup(kind: AceKind, id: string, owner: AceOwner, catalog: AceCatalog): AceParam[] | undefined | null {
  const set = (owner.kind === 'plugin' ? catalog.plugins[owner.id] : catalog.behaviors[owner.id])
    ?? addonDefinition(owner.kind, owner.id)?.aces;
  if (!set) return null;
  const own = set[kind][id];
  if (own) return own;
  // Common ACEs belong to plugin objects, never to System or to behaviors.
  if (owner.kind === 'plugin' && owner.id !== 'system') return catalog.common[kind][id];
  return undefined;
}

function ownerLabel(owner: AceOwner): string {
  if (owner.kind === 'plugin' && owner.id === 'system') return 'the System object';
  return `the ${owner.id} ${owner.kind}`;
}

/**
 * Check one condition or action against the catalogue: its ID, and, when its
 * parameters are stored as a keyed object, their names and combo choices.
 */
export function checkAce(
  kind: AceKind,
  ace: { id: string; parameters?: unknown },
  owner: AceOwner,
  catalog: AceCatalog = ACE_CATALOG,
): AceProblem[] {
  const params = lookup(kind, ace.id, owner, catalog);
  if (params === null) return [];
  const noun = kind === 'conditions' ? 'condition' : 'action';
  const release = catalog.release.replace('-', '.');
  if (params === undefined) {
    return [{
      code: 'unknown-ace',
      message: `Construct ${release} defines no ${noun} "${ace.id}" for ${ownerLabel(owner)}.`,
    }];
  }

  const problems: AceProblem[] = [];
  const given = ace.parameters;
  if (given === undefined || given === null) {
    if (params.length > 0) {
      problems.push({
        code: 'missing-parameter',
        message: `The ${noun} "${ace.id}" of ${ownerLabel(owner)} takes parameter(s) ${params.map(p => `"${p.id}"`).join(', ')}, and none are given.`,
      });
    }
    return problems;
  }
  if (typeof given !== 'object' || Array.isArray(given)) return problems;

  const values = given as Record<string, unknown>;
  const byId = new Map(params.map(p => [p.id, p]));
  const unknown = Object.keys(values).filter(k => !byId.has(k));
  if (unknown.length > 0) {
    problems.push({
      code: 'unknown-parameter',
      message: `The ${noun} "${ace.id}" of ${ownerLabel(owner)} has no parameter(s) ${unknown.map(k => `"${k}"`).join(', ')}. Its parameters are ${params.map(p => `"${p.id}"`).join(', ') || '(none)'}.`,
    });
  }
  const missing = params.filter(p => !(p.id in values));
  if (missing.length > 0) {
    problems.push({
      code: 'missing-parameter',
      message: `The ${noun} "${ace.id}" of ${ownerLabel(owner)} is missing parameter(s) ${missing.map(p => `"${p.id}"`).join(', ')}.`,
    });
  }
  for (const p of params) {
    if (!p.items || !(p.id in values)) continue;
    const value = values[p.id];
    if (typeof value !== 'string' || !p.items.includes(value)) {
      problems.push({
        code: 'invalid-choice',
        message: `Parameter "${p.id}" of the ${noun} "${ace.id}" is ${JSON.stringify(value)}; ${ownerLabel(owner)} accepts ${p.items.map(i => `"${i}"`).join(', ')}.`,
      });
    }
  }
  return problems;
}

/** What resolving an event's objectClass and behaviorType needs from the project. */
export interface AceContext {
  /** The plugin ID behind an object type or family name, or undefined when the project has neither. */
  pluginOf(objectClass: string): string | undefined;
  /**
   * The behavior ID behind a behavior name on an object type or family,
   * looking at the families an object belongs to and the members of a family.
   */
  behaviorOf(objectClass: string, behaviorName: string): string | undefined;
}

interface Declared {
  pluginId?: string;
  behaviors: Map<string, string>;
  members: string[];
}

function declared(raw: Record<string, unknown>): Declared {
  const behaviors = new Map<string, string>();
  for (const b of Array.isArray(raw.behaviorTypes) ? raw.behaviorTypes as Array<Record<string, unknown>> : []) {
    if (typeof b.name === 'string' && typeof b.behaviorId === 'string') behaviors.set(b.name, b.behaviorId);
  }
  return {
    pluginId: typeof raw['plugin-id'] === 'string' ? raw['plugin-id'] as string : undefined,
    behaviors,
    members: Array.isArray(raw.members) ? (raw.members as unknown[]).filter((m): m is string => typeof m === 'string') : [],
  };
}

/** Build the objectClass and behavior resolution for a project. Unreadable object types are left out. */
export async function buildAceContext(reader: Construct3ProjectReader): Promise<AceContext> {
  const types = new Map<string, Declared>();
  for (const name of await reader.listObjectTypes()) {
    try {
      types.set(name, declared(await reader.readObjectType(name) as unknown as Record<string, unknown>));
    } catch {
      // An unreadable object type is reported by other checks; its ACEs are skipped here.
    }
  }
  const families = new Map<string, Declared>();
  for (const [name, family] of await reader.readAllFamilies()) {
    families.set(name, declared(family as unknown as Record<string, unknown>));
  }
  return fromDeclarations(types, families);
}

function fromDeclarations(types: Map<string, Declared>, families: Map<string, Declared>): AceContext {
  return {
    pluginOf(objectClass) {
      if (objectClass === 'System') return 'system';
      return (types.get(objectClass) ?? families.get(objectClass))?.pluginId;
    },
    behaviorOf(objectClass, behaviorName) {
      const candidates: Array<Declared | undefined> = [types.get(objectClass) ?? families.get(objectClass)];
      if (types.has(objectClass)) {
        for (const family of families.values()) if (family.members.includes(objectClass)) candidates.push(family);
      }
      const family = families.get(objectClass);
      if (family) for (const member of family.members) candidates.push(types.get(member));
      for (const c of candidates) {
        const id = c?.behaviors.get(behaviorName);
        if (id) return id;
      }
      return undefined;
    },
  };
}

/** The owner of an ACE as stored in an event, or undefined when it cannot be resolved. */
export function aceOwner(ace: { objectClass?: unknown; behaviorType?: unknown }, context: AceContext): AceOwner | undefined {
  if (typeof ace.objectClass !== 'string') return undefined;
  if (typeof ace.behaviorType === 'string') {
    const id = context.behaviorOf(ace.objectClass, ace.behaviorType);
    return id ? { kind: 'behavior', id } : undefined;
  }
  const plugin = context.pluginOf(ace.objectClass);
  return plugin ? { kind: 'plugin', id: plugin } : undefined;
}

/** One problem found in an event list, located by the ACE's SID. */
export interface EventAceProblem extends AceProblem {
  kind: AceKind;
  aceId: string;
  objectClass: string;
  sid?: number;
}

/**
 * Check every standard condition and action in `events` and their sub-events.
 * Function calls, custom action calls, scripts and comments are not ACEs of
 * the catalogue and are skipped. `only`, when given, limits the check to ACEs
 * whose SID it holds.
 */
export function checkEventAces(
  events: unknown,
  context: AceContext,
  only?: Set<number>,
  catalog: AceCatalog = ACE_CATALOG,
): EventAceProblem[] {
  const problems: EventAceProblem[] = [];
  const walk = (list: unknown, depth: number): void => {
    if (!Array.isArray(list) || depth > 64) return;
    for (const event of list as Array<Record<string, unknown>>) {
      if (!event || typeof event !== 'object') continue;
      for (const kind of ['conditions', 'actions'] as const) {
        const items = event[kind];
        if (!Array.isArray(items)) continue;
        for (const ace of items as Array<Record<string, unknown>>) {
          if (!ace || typeof ace.id !== 'string' || typeof ace.objectClass !== 'string') continue;
          const sid = typeof ace.sid === 'number' ? ace.sid : undefined;
          if (only && (sid === undefined || !only.has(sid))) continue;
          const owner = aceOwner(ace, context);
          if (!owner) continue;
          for (const p of checkAce(kind, { id: ace.id, parameters: ace.parameters }, owner, catalog)) {
            problems.push({ ...p, kind, aceId: ace.id, objectClass: ace.objectClass, sid });
          }
        }
      }
      walk(event.children, depth + 1);
    }
  };
  walk(events, 0);
  return problems;
}

/** A problem worded for a tool warning: which ACE, on which object, and what is wrong. */
export function describeEventAceProblem(p: EventAceProblem): string {
  const noun = p.kind === 'conditions' ? 'Condition' : 'Action';
  return `${noun} "${p.aceId}" on "${p.objectClass}"${p.sid !== undefined ? ` (SID ${p.sid})` : ''}: ${p.message}`;
}

/** Collect the SIDs of every condition and action in an event list. */
export function collectAceSids(events: unknown, into: Set<number> = new Set()): Set<number> {
  if (!Array.isArray(events)) return into;
  for (const event of events as Array<Record<string, unknown>>) {
    if (!event || typeof event !== 'object') continue;
    for (const kind of ['conditions', 'actions']) {
      for (const ace of Array.isArray(event[kind]) ? event[kind] as Array<Record<string, unknown>> : []) {
        if (typeof ace?.sid === 'number') into.add(ace.sid);
      }
    }
    collectAceSids(event.children, into);
  }
  return into;
}

/** The block's own conditions and actions by SID, as JSON, to tell afterwards which ones an edit touched. */
export function aceSnapshot(event: Record<string, unknown>): Map<number, string> {
  const snapshot = new Map<number, string>();
  for (const kind of ['conditions', 'actions']) {
    for (const ace of Array.isArray(event[kind]) ? event[kind] as Array<Record<string, unknown>> : []) {
      if (typeof ace?.sid === 'number') snapshot.set(ace.sid, JSON.stringify(ace));
    }
  }
  return snapshot;
}

/** SIDs of the block's own conditions and actions that are new or changed since `before`. */
export function changedAceSids(before: Map<number, string>, event: Record<string, unknown>): Set<number> {
  const changed = new Set<number>();
  for (const [sid, json] of aceSnapshot(event)) if (before.get(sid) !== json) changed.add(sid);
  return changed;
}

/** Every condition and action in an event tree by SID, as JSON, to tell afterwards which ones an edit touched. */
export function aceTreeSnapshot(events: unknown, into: Map<number, string> = new Map(), depth = 0): Map<number, string> {
  if (!Array.isArray(events) || depth > 64) return into;
  for (const event of events as Array<Record<string, unknown>>) {
    if (!event || typeof event !== 'object') continue;
    for (const [sid, json] of aceSnapshot(event)) into.set(sid, json);
    aceTreeSnapshot(event.children, into, depth + 1);
  }
  return into;
}

/** SIDs of the conditions and actions anywhere in `events` that are new or changed since `before`. */
export function changedAceSidsInTree(before: Map<number, string>, events: unknown): Set<number> {
  const changed = new Set<number>();
  for (const [sid, json] of aceTreeSnapshot(events)) if (before.get(sid) !== json) changed.add(sid);
  return changed;
}
